// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // VAPID key: Firebase Console → Project settings → Cloud Messaging →
  //            Web Push certificates → Generate key pair
  static const String vapidKey = 'BLty2OHzNFK1mfF_oSnqlKnZnAsGlcOfOMKeiEOd-M_E5Y_tKDKVk19bZOKeszfoHkviTn1w5I3hgqU5dovb-yY';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfkQzNw18oRejjQ3wOPq6YxcpG_rDNxI4',
    appId: '1:775783515922:web:5871609a2920e4c8d7d5cb',
    messagingSenderId: '775783515922',
    projectId: 'foco-pedagogico',
    storageBucket: 'foco-pedagogico.firebasestorage.app',
    authDomain: 'foco-pedagogico.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB2nNE4fHuIyIEf--H0LG71_gfuAzO0bM',
    appId: '1:775783515922:android:a16e6ab9dc2eb1d4d7d5cb',
    messagingSenderId: '775783515922',
    projectId: 'foco-pedagogico',
    storageBucket: 'foco-pedagogico.firebasestorage.app',
  );
}
